// eventdetails.dart

List<Map<String, dynamic>> eventDetails = [
  {
    'eventTitle': "Flutter UI Design Workshop",
    'eventDate': "30 January 2024",
    'eventTime': "8:00 am - 12:00 pm",
    'eventLocation': "Multi Perpose Hall, KICT",
    'eventPicture': "assets/images/flutter.png",
    'eventInfo': "Learn how to design beautiful UIs with Flutter",
    'geotag': {'latitude': 51.5074, 'longitude': 0.1278},
    'isJoin': false,
  },
  {
    'eventTitle': "Data Science Seminar",
    'eventDate': "15 February 2024",
    'eventTime': "10:00 am - 2:00 pm",
    'eventLocation': "Conference Room, KICT",
    'eventPicture': "assets/images/datascience.png",
    'eventInfo': "Explore the world of data science",
    'geotag': {'latitude': 51.5074, 'longitude': 0.1278},
    'isJoin': false,
  },
  {
    'eventTitle': "Cybersecurity Workshop",
    'eventDate': "20 March 2024",
    'eventTime': "9:00 am - 1:00 pm",
    'eventLocation': "Lab 5, KICT",
    'eventPicture': "assets/images/cybersecurity.png",
    'eventInfo': "Learn about the latest trends in cybersecurity",
    'geotag': {'latitude': 51.5074, 'longitude': 0.1278},
    'isJoin': false,
  },
  {
    'eventTitle': "AI and Machine Learning Talk",
    'eventDate': "25 April 2024",
    'eventTime': "11:00 am - 3:00 pm",
    'eventLocation': "Auditorium, KICT",
    'eventPicture': "assets/images/ai_ml.png",
    'eventInfo': "Discover the power of AI and machine learning",
    'geotag': {'latitude': 51.5074, 'longitude': 0.1278},
    'isJoin': false,
  },
  {
    'eventTitle': "Web Development Bootcamp",
    'eventDate': "30 May 2024",
    'eventTime': "8:00 am - 12:00 pm",
    'eventLocation': "Lab 6, KICT",
    'eventPicture': "assets/images/webdev.png",
    'eventInfo': "Master the fundamentals of web development",
    'geotag': {'latitude': 51.5074, 'longitude': 0.1278},
    'isJoin': false,
  },
  {
    'eventTitle': "Cloud Computing Symposium",
    'eventDate': "10 June 2024",
    'eventTime': "9:00 am - 1:00 pm",
    'eventLocation': "Conference Room, KICT",
    'eventPicture': "assets/images/cloudcomputing.png",
    'eventInfo': "Explore the future of cloud computing",
    'geotag': {'latitude': 51.5074, 'longitude': 0.1278},
    'isJoin': false,
  },
];
